# Generated by Django 3.1 on 2020-08-16 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
