# Generated by Django 3.1 on 2020-08-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='count',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='photo',
            name='money',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
