# Generated by Django 3.0.8 on 2020-08-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='area',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='photo',
            name='text',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=13),
        ),
    ]
