# Generated by Django 3.1 on 2020-08-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='photo',
            name='area',
            field=models.TextField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='photo',
            name='count',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='photo',
            name='money',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
