# Generated by Django 3.1 on 2020-08-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200822_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
