# Generated by Django 3.0.8 on 2020-08-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200728_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('fruit', '과일'), ('vegetable', '채소'), ('meat', '정육'), ('dairy', '계란/유제품'), ('fish', '수산/건어물'), ('main_food', '쌀/김치/반찬'), ('bakery', '베이커리'), ('dessert', '디저트/음료'), ('health_food', '가공/건강식품'), ('household', '생활용품')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='deal',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
