# Generated by Django 3.0.8 on 2020-08-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20200803_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parentComment',
        ),
        migrations.AlterField(
            model_name='photo',
            name='deal',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=50),
        ),
    ]
