# Generated by Django 3.0.8 on 2020-08-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20200804_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertedimage',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inserted_image', to='photo.Photo'),
        ),
    ]
