# Generated by Django 3.1 on 2020-08-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20200822_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='deal',
            field=models.CharField(choices=[('모집중', '모집중'), ('모집완료', '모집완료')], default='Y', max_length=50),
        ),
    ]
