# Generated by Django 3.0.8 on 2020-08-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20200803_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['updated']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='writer',
        ),
    ]
