# Generated by Django 3.1 on 2020-08-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20200810_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['updated']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parentComment',
        ),
        migrations.AddField(
            model_name='photo',
            name='area',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('fruit', '과일'), ('vegetable', '채소'), ('meat', '정육'), ('dairy', '계란/유제품'), ('fish', '수산/건어물'), ('main_food', '쌀/김치/반찬'), ('bakery', '베이커리'), ('dessert', '디저트/음료'), ('health_food', '가공/건강식품'), ('household', '생활용품')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='deal',
            field=models.CharField(choices=[('Y', '모집중'), ('N', '모집완료')], default='Y', max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='text',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=13),
        ),
    ]
