# Generated by Django 3.1 on 2020-08-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20200822_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='deal',
            field=models.CharField(choices=[('모집 중', '모집 중'), ('모집 완료', '모집 완료')], default='모집 중', max_length=50),
        ),
    ]
