# Generated by Django 3.0.8 on 2020-08-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20200803_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='writer',
            new_name='username',
        ),
    ]
