# Generated by Django 3.0.8 on 2020-08-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20200808_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=200),
        ),
    ]
