# Generated by Django 3.1 on 2020-08-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200815_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='user_photo/%Y/%m/%d'),
        ),
    ]
