# Generated by Django 3.1 on 2020-08-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='living',
            field=models.CharField(default='', max_length=200, verbose_name='동네'),
        ),
    ]
