# Generated by Django 3.0.8 on 2020-08-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200815_1543'),
        ('accounts', '0008_alarm'),
    ]

    operations = [
    ]
